2024-05-27 14:34:53,575: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:34:58,195: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\planner\settings.py changed, reloading.
2024-05-27 14:34:58,924: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:35:02,374: INFO - todos.views views.py (line42). Testing the logger!
2024-05-27 14:35:02,376: ERROR - todos.views views.py (line51). User with ID 2 does not exist
2024-05-27 14:35:02,379: WARNING - django.request log.py (line241). Bad Request: /api/v1/post_todo/
2024-05-27 14:35:47,605: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:35:48,265: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:36:15,060: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:36:15,992: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:36:36,460: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:36:37,347: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:36:49,314: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:36:50,162: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:37:20,980: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:37:21,887: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:37:51,704: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:37:52,575: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
2024-05-27 14:38:02,352: INFO - todos.views views.py (line22). Testing the logger!
2024-05-27 14:38:14,140: INFO - todos.views views.py (line35). Testing the logger!
2024-05-27 14:38:31,854: INFO - todos.views views.py (line73). Testing the logger!
2024-05-27 14:38:38,426: INFO - todos.views views.py (line73). Testing the logger!
2024-05-27 14:38:38,430: ERROR - todos.views views.py (line82). User with ID 2 does not exist
2024-05-27 14:38:38,432: WARNING - django.request log.py (line241). Bad Request: /api/v1/post_todo_generics/
2024-05-27 14:39:24,745: INFO - django.utils.autoreload autoreload.py (line266). C:\Users\Shahrukh\OneDrive\Shahrukh\Coding\Python_Django\18.Django_logging\django_logging\todos\views.py changed, reloading.
2024-05-27 14:39:25,462: INFO - django.utils.autoreload autoreload.py (line668). Watching for file changes with StatReloader
